// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
/* eslint-disable @typescript-eslint/no-unused-vars */

import type {
  Session,
  Request,
  AgentAnalysis,
  AnalysisRequest,
  ApiResponse,
  PaginatedData,
  AgentModel,
  ModelListResponse,
  AppSettings,
  UpdateInfo,
} from '@/types'
import { bindings, config } from '../../wailsjs/go/models'

import {
  ActivateSession,
  CreateSession,
  DeleteSession,
  ExportSessions,
  GetSession,
  ImportSessions,
  ListSessions,
  UpdateSession,
} from '../../wailsjs/go/bindings/SessionAPI'
import {
  ClearRequests,
  ComposeRequest,
  DeleteRequest,
  ExportRequest,
  GetRequest,
  ListRequests,
  ReplayRequest,
} from '../../wailsjs/go/bindings/RequestAPI'
import {
  Analyze,
  CancelAnalysis,
  ListModels,
  ListProviders,
} from '../../wailsjs/go/bindings/AgentAPI'
import { isWailsRuntime } from '../../wailsjs/runtime/runtime'
import {
  DownloadCert,
  GetCertInfo,
  GetConfig,
  GetSettings,
  GetLocalIPAddresses,
  GetAgentProviderKey,
  UpdateAgentConfig,
  UpdateSettings,
  UpsertModel,
  DeleteModel,
} from '../../wailsjs/go/bindings/ConfigAPI'
import {
  Start,
  Status,
  Stop,
} from '../../wailsjs/go/bindings/ProxyAPI'


const normalizeResponse = <T>(response: { code: number; message?: string; data?: unknown }): ApiResponse<T> => ({
  code: response.code,
  message: response.message || '',
  data: response.data as T | undefined,
})

export const sessionApi = {
  list: async (): Promise<ApiResponse<PaginatedData<Session>>> => {
    return normalizeResponse<PaginatedData<Session>>(await ListSessions())
  },

  get: async (id: string): Promise<ApiResponse<Session>> => {
    return normalizeResponse<Session>(await GetSession(id))
  },

  create: async (data: { name: string; description?: string }): Promise<ApiResponse<Session>> => {
    return normalizeResponse<Session>(await CreateSession(new bindings.CreateSessionRequest({
      name: data.name,
      description: data.description || '',
    })))
  },

  delete: async (id: string): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await DeleteSession(id))
  },

  update: async (id: string, data: { name?: string; description?: string }): Promise<ApiResponse<Session>> => {
    return normalizeResponse<Session>(await UpdateSession(id, new bindings.UpdateSessionRequest(data)))
  },

  activate: async (id: string): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await ActivateSession(id))
  },

  exportAll: async (): Promise<ApiResponse<{ filename: string; content: string }>> => {
    return normalizeResponse<{ filename: string; content: string }>(await ExportSessions())
  },

  importAll: async (contentBase64: string): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await ImportSessions(contentBase64))
  },
}

export const requestApi = {
  list: async (params: {
    session_id?: string
    host?: string
    method?: string
    status_code?: number
    search?: string
  } = {}): Promise<ApiResponse<PaginatedData<Request>>> => {
    return normalizeResponse<PaginatedData<Request>>(await ListRequests(new bindings.RequestListOptions({
      session_id: params.session_id || '',
      host: params.host || '',
      method: params.method || '',
      search: params.search || '',
      sort_by: 'created_at',
      sort_order: 'desc',
      status_code: params.status_code || 0,
    })))
  },

  get: async (sessionId: string, id: string): Promise<ApiResponse<Request>> => {
    return normalizeResponse<Request>(await GetRequest(sessionId, id))
  },

  delete: async (sessionId: string, id: string): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await DeleteRequest(sessionId, id))
  },

  clear: async (sessionId?: string): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await ClearRequests(sessionId || ''))
  },

  replay: async (sessionId: string, id: string): Promise<ApiResponse<Request>> => {
    return normalizeResponse<Request>(await ReplayRequest(sessionId, id, new bindings.ReplayRequestOptions({
      headers: {},
      body: '',
    })))
  },

  compose: async (opts: { method: string; url: string; headers: Record<string, string[]>; body: string }): Promise<ApiResponse<any>> => {
    return normalizeResponse<any>(await ComposeRequest(new bindings.ComposeRequestOptions({
      method: opts.method,
      url: opts.url,
      headers: opts.headers,
      body: opts.body,
    })))
  },

  export: async (sessionId: string, id: string, format: 'curl' | 'har' = 'curl'): Promise<string> => {
    const res = normalizeResponse<string>(await ExportRequest(sessionId, id, format))
    return res.data || ''
  },
}

export const agentApi = {
  analyze: async (data: AnalysisRequest): Promise<ApiResponse<{ analysis_id: string; model?: AgentModel }>> => {
    const response = await Analyze(new bindings.AnalyzeRequest({
      request_id: data.request_id || '',
      session_id: data.session_id || '',
      query: data.query || '',
      model_id: data.model_id || '',
    }))

    return {
      code: response.code,
      message: response.message || '',
      data: response.analysis_id
        ? {
            analysis_id: response.analysis_id,
            model: response.model as unknown as AgentModel | undefined,
          }
        : undefined,
    }
  },

  cancel: async (analysisId: string): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await CancelAnalysis(analysisId))
  },

  listModels: async (): Promise<ApiResponse<ModelListResponse>> => {
    return normalizeResponse<ModelListResponse>(await ListModels())
  },

  listProviders: async (): Promise<ApiResponse<{ providers: import('@/types').ProviderInfo[] }>> => {
    return normalizeResponse<{ providers: import('@/types').ProviderInfo[] }>(await ListProviders())
  },


  getSessionContext: async (sessionId: string): Promise<import('@/types').SessionContextStats> => {
    const w: any = window as any
    if (w?.go?.bindings?.AgentAPI?.GetSessionContext) {
      return await w.go.bindings.AgentAPI.GetSessionContext(sessionId) as import('@/types').SessionContextStats
    }
    return {
      code: 0,
      session_id: sessionId,
      has_history: false,
      message_count: 0,
      estimated_tokens: 0,
      active_model: '',
      active_provider: '',
      active_max_tokens: 0,
      active_temperature: 0,
      available_models: 0,
    }
  },

  getChatHistory: async (sessionId: string): Promise<ApiResponse<{ messages: Array<{ role: string; content: string; created_at: string }> }>> => {
    const w: any = window as any
    if (w?.go?.bindings?.AgentAPI?.GetChatHistory) {
      return normalizeResponse<{ messages: Array<{ role: string; content: string; created_at: string }> }>(
        await w.go.bindings.AgentAPI.GetChatHistory(sessionId)
      )
    }
    return { code: 0, message: '', data: { messages: [] } }
  },

  clearChatHistory: async (sessionId: string): Promise<ApiResponse<void>> => {
    const w: any = window as any
    if (w?.go?.bindings?.AgentAPI?.ClearSessionMemory) {
      return normalizeResponse<void>(await w.go.bindings.AgentAPI.ClearSessionMemory(sessionId))
    }
    return { code: 0, message: '' }
  },

  listAnalyses: async (_requestId: string): Promise<ApiResponse<AgentAnalysis[]>> => {
    return {
      code: 50001,
      message: 'ListAnalyses is not exposed by current Wails bindings',
    } as ApiResponse<AgentAnalysis[]>
  },

  getAnalysis: async (_id: string): Promise<ApiResponse<AgentAnalysis>> => {
    return {
      code: 50001,
      message: 'GetAnalysis is not exposed by current Wails bindings',
    } as ApiResponse<AgentAnalysis>
  },
}

export const fetchModels = async () => {
  const response = await agentApi.listModels()
  return response.data
}


export const proxyApi = {
  status: async (): Promise<ApiResponse<{ running: boolean }>> => {
    return normalizeResponse<{ running: boolean }>(await Status())
  },

  start: async (): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await Start())
  },

  stop: async (): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await Stop())
  },
}

export const configApi = {
  get: async (): Promise<ApiResponse<{
    server: { host: string; port: number }
    proxy: {
      port: number
      http: { enabled: boolean }
      https: { enabled: boolean; mitm: boolean }
      socks5: { enabled: boolean }
    }
    agent: {
      provider: string
      model: string
      max_tokens: number
      temperature: number
    }
  }>> => {
    return normalizeResponse<{
      server: { host: string; port: number }
      proxy: {
        port: number
        http: { enabled: boolean }
        https: { enabled: boolean; mitm: boolean }
        socks5: { enabled: boolean }
      }
      agent: {
        provider: string
        model: string
        max_tokens: number
        temperature: number
      }
    }>(await GetConfig())
  },

  updateAgent: async (data: {
    provider?: string
    api_type?: string
    api_key?: string
    base_url?: string
    model?: string
    max_tokens?: number
    temperature?: number
  }): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await UpdateAgentConfig(new bindings.UpdateAgentConfigRequest(data)))
  },

  getAgentProviderKey: async (provider: string): Promise<ApiResponse<{ api_key: string, base_url?: string, api_type?: string }>> => {
    return normalizeResponse<{ api_key: string, base_url?: string, api_type?: string }>(await GetAgentProviderKey(provider))
  },

  upsertAgentProvider: async (data: { id: string; name: string; api_type: string; api_key?: string; base_url?: string }): Promise<ApiResponse<any>> => {
    const w: any = window as any
    if (w?.go?.bindings?.ConfigAPI?.UpsertAgentProvider) {
      return normalizeResponse<any>(await w.go.bindings.ConfigAPI.UpsertAgentProvider(new bindings.UpsertAgentProviderRequest(data)))
    }
    return { code: 50001, message: 'UpsertAgentProvider not available' }
  },

  deleteAgentProvider: async (id: string): Promise<ApiResponse<void>> => {
    const w: any = window as any
    if (w?.go?.bindings?.ConfigAPI?.DeleteAgentProvider) {
      return normalizeResponse<void>(await w.go.bindings.ConfigAPI.DeleteAgentProvider(new bindings.DeleteAgentProviderRequest({ id })))
    }
    return { code: 50001, message: 'DeleteAgentProvider not available' }
  },

  upsertModel: async (data: { provider: string; id: string; name: string; context: number; output: number }): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await UpsertModel(new bindings.UpsertModelRequest(data)))
  },

  deleteModel: async (provider: string, id: string): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await DeleteModel(new bindings.DeleteModelRequest({ provider, id })))
  },

  getSettings: async (): Promise<ApiResponse<AppSettings>> => {
    return normalizeResponse<AppSettings>(await GetSettings())
  },

  getLocalIPAddresses: async (): Promise<ApiResponse<Array<{ interface_name: string; ip_address: string }>>> => {
    return normalizeResponse<Array<{ interface_name: string; ip_address: string }>>(await GetLocalIPAddresses())
  },

  updateSettings: async (data: AppSettings): Promise<ApiResponse<AppSettings>> => {
    return normalizeResponse<AppSettings>(await UpdateSettings(data as never))
  },

  getCertInfo: async (): Promise<ApiResponse<{ path: string; exists: boolean; size: number; modified: string; download: string }>> => {
    return normalizeResponse<{ path: string; exists: boolean; size: number; modified: string; download: string }>(await GetCertInfo())
  },

  downloadCert: async (): Promise<ApiResponse<{ filename: string; content: string }>> => {
    return normalizeResponse<{ filename: string; content: string }>(await DownloadCert())
  },
}

const callUpdater = async (method: string, ...args: any[]): Promise<any> => {
  const w = window as any
  if (w?.go?.bindings?.UpdaterAPI?.[method]) {
    return await w.go.bindings.UpdaterAPI[method](...args)
  }
  return { code: 50001, message: 'Updater not available' }
}

export const updaterApi = {
  getVersion: async (): Promise<ApiResponse<{ version: string }>> => {
    return normalizeResponse<{ version: string }>(await callUpdater('GetVersion'))
  },
  checkForUpdate: async (): Promise<ApiResponse<UpdateInfo>> => {
    return normalizeResponse<UpdateInfo>(await callUpdater('CheckForUpdate'))
  },
  performUpdate: async (): Promise<ApiResponse<void>> => {
    return normalizeResponse<void>(await callUpdater('PerformUpdate'))
  },
}
