// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1) {
  return window['go']['bindings']['AgentAPI']['Analyze'](arg1);
}

export function CancelAnalysis(arg1) {
  return window['go']['bindings']['AgentAPI']['CancelAnalysis'](arg1);
}

export function ClearSessionMemory(arg1) {
  return window['go']['bindings']['AgentAPI']['ClearSessionMemory'](arg1);
}

export function GetChatHistory(arg1) {
  return window['go']['bindings']['AgentAPI']['GetChatHistory'](arg1);
}

export function GetSessionContext(arg1) {
  return window['go']['bindings']['AgentAPI']['GetSessionContext'](arg1);
}

export function ListModels() {
  return window['go']['bindings']['AgentAPI']['ListModels']();
}

export function ListProviders() {
  return window['go']['bindings']['AgentAPI']['ListProviders']();
}

export function SendIntervention(arg1) {
  return window['go']['bindings']['AgentAPI']['SendIntervention'](arg1);
}
