// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function Analyze(arg1:bindings.AnalyzeRequest):Promise<bindings.AnalyzeResponse>;

export function CancelAnalysis(arg1:string):Promise<bindings.SessionResponse>;

export function ClearSessionMemory(arg1:string):Promise<bindings.SessionResponse>;

export function GetChatHistory(arg1:string):Promise<bindings.SessionResponse>;

export function GetSessionContext(arg1:string):Promise<bindings.SessionContextStats>;

export function ListModels():Promise<bindings.SessionResponse>;

export function ListProviders():Promise<bindings.SessionResponse>;
