// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAgentProvider(arg1) {
  return window['go']['bindings']['ConfigAPI']['DeleteAgentProvider'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['bindings']['ConfigAPI']['DeleteModel'](arg1);
}

export function DownloadCert() {
  return window['go']['bindings']['ConfigAPI']['DownloadCert']();
}

export function GetAgentProviderKey(arg1) {
  return window['go']['bindings']['ConfigAPI']['GetAgentProviderKey'](arg1);
}

export function GetCertInfo() {
  return window['go']['bindings']['ConfigAPI']['GetCertInfo']();
}

export function GetConfig() {
  return window['go']['bindings']['ConfigAPI']['GetConfig']();
}

export function GetLocalIPAddresses() {
  return window['go']['bindings']['ConfigAPI']['GetLocalIPAddresses']();
}

export function GetSettings() {
  return window['go']['bindings']['ConfigAPI']['GetSettings']();
}

export function UpdateAgentConfig(arg1) {
  return window['go']['bindings']['ConfigAPI']['UpdateAgentConfig'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['bindings']['ConfigAPI']['UpdateSettings'](arg1);
}

export function UpsertAgentProvider(arg1) {
  return window['go']['bindings']['ConfigAPI']['UpsertAgentProvider'](arg1);
}

export function UpsertModel(arg1) {
  return window['go']['bindings']['ConfigAPI']['UpsertModel'](arg1);
}
