// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {config} from '../models';

export function DeleteAgentProvider(arg1:bindings.DeleteAgentProviderRequest):Promise<bindings.SessionResponse>;

export function DeleteModel(arg1:bindings.DeleteModelRequest):Promise<bindings.SessionResponse>;

export function DownloadCert():Promise<bindings.SessionResponse>;

export function GetAgentProviderKey(arg1:string):Promise<bindings.SessionResponse>;

export function GetCertInfo():Promise<bindings.SessionResponse>;

export function GetConfig():Promise<bindings.SessionResponse>;

export function GetLocalIPAddresses():Promise<bindings.SessionResponse>;

export function GetSettings():Promise<bindings.SessionResponse>;

export function UpdateAgentConfig(arg1:bindings.UpdateAgentConfigRequest):Promise<bindings.SessionResponse>;

export function UpdateSettings(arg1:config.AppSettings):Promise<bindings.SessionResponse>;

export function UpsertAgentProvider(arg1:bindings.UpsertAgentProviderRequest):Promise<bindings.SessionResponse>;

export function UpsertModel(arg1:bindings.UpsertModelRequest):Promise<bindings.SessionResponse>;
