// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function Start():Promise<bindings.SessionResponse>;

export function Status():Promise<bindings.SessionResponse>;

export function Stop():Promise<bindings.SessionResponse>;
