// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Start() {
  return window['go']['bindings']['ProxyAPI']['Start']();
}

export function Status() {
  return window['go']['bindings']['ProxyAPI']['Status']();
}

export function Stop() {
  return window['go']['bindings']['ProxyAPI']['Stop']();
}
