// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRequests(arg1) {
  return window['go']['bindings']['RequestAPI']['ClearRequests'](arg1);
}

export function ComposeRequest(arg1) {
  return window['go']['bindings']['RequestAPI']['ComposeRequest'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['bindings']['RequestAPI']['DeleteRequest'](arg1, arg2);
}

export function ExportRequest(arg1, arg2, arg3) {
  return window['go']['bindings']['RequestAPI']['ExportRequest'](arg1, arg2, arg3);
}

export function FindInSession(arg1) {
  return window['go']['bindings']['RequestAPI']['FindInSession'](arg1);
}

export function GetRequest(arg1, arg2) {
  return window['go']['bindings']['RequestAPI']['GetRequest'](arg1, arg2);
}

export function ListRequests(arg1) {
  return window['go']['bindings']['RequestAPI']['ListRequests'](arg1);
}

export function ReplayRequest(arg1, arg2, arg3) {
  return window['go']['bindings']['RequestAPI']['ReplayRequest'](arg1, arg2, arg3);
}

export function SetOnComplete(arg1) {
  return window['go']['bindings']['RequestAPI']['SetOnComplete'](arg1);
}

export function SetOnRequest(arg1) {
  return window['go']['bindings']['RequestAPI']['SetOnRequest'](arg1);
}
