// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {storage} from '../models';

export function ClearRequests(arg1:string):Promise<bindings.SessionResponse>;

export function ComposeRequest(arg1:bindings.ComposeRequestOptions):Promise<bindings.SessionResponse>;

export function DeleteRequest(arg1:string,arg2:string):Promise<bindings.SessionResponse>;

export function ExportRequest(arg1:string,arg2:string,arg3:string):Promise<bindings.SessionResponse>;

export function FindInSession(arg1:storage.FindInSessionOptions):Promise<bindings.SessionResponse>;

export function GetRequest(arg1:string,arg2:string):Promise<bindings.SessionResponse>;

export function ListRequests(arg1:bindings.RequestListOptions):Promise<bindings.SessionResponse>;

export function ReplayRequest(arg1:string,arg2:string,arg3:bindings.ReplayRequestOptions):Promise<bindings.SessionResponse>;

export function SetOnComplete(arg1:any):Promise<void>;

export function SetOnRequest(arg1:any):Promise<void>;
