// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function ActivateSession(arg1:string):Promise<bindings.SessionResponse>;

export function CreateSession(arg1:bindings.CreateSessionRequest):Promise<bindings.SessionResponse>;

export function DeleteSession(arg1:string):Promise<bindings.SessionResponse>;

export function ExportSessions():Promise<bindings.SessionResponse>;

export function GetSession(arg1:string):Promise<bindings.SessionResponse>;

export function ImportSessions(arg1:string):Promise<bindings.SessionResponse>;

export function ListSessions():Promise<bindings.SessionResponse>;

export function UpdateSession(arg1:string,arg2:bindings.UpdateSessionRequest):Promise<bindings.SessionResponse>;
