// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateSession(arg1) {
  return window['go']['bindings']['SessionAPI']['ActivateSession'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['bindings']['SessionAPI']['CreateSession'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['bindings']['SessionAPI']['DeleteSession'](arg1);
}

export function ExportSessions() {
  return window['go']['bindings']['SessionAPI']['ExportSessions']();
}

export function GetSession(arg1) {
  return window['go']['bindings']['SessionAPI']['GetSession'](arg1);
}

export function ImportSessions(arg1) {
  return window['go']['bindings']['SessionAPI']['ImportSessions'](arg1);
}

export function ListSessions() {
  return window['go']['bindings']['SessionAPI']['ListSessions']();
}

export function UpdateSession(arg1, arg2) {
  return window['go']['bindings']['SessionAPI']['UpdateSession'](arg1, arg2);
}
