// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['bindings']['UpdaterAPI']['CheckForUpdate']();
}

export function GetVersion() {
  return window['go']['bindings']['UpdaterAPI']['GetVersion']();
}

export function PerformUpdate() {
  return window['go']['bindings']['UpdaterAPI']['PerformUpdate']();
}
