// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['bindings']['UpdaterAPI']['CheckForUpdate']();
}

export function DownloadUpdate() {
  return window['go']['bindings']['UpdaterAPI']['DownloadUpdate']();
}

export function GetVersion() {
  return window['go']['bindings']['UpdaterAPI']['GetVersion']();
}

export function OpenDownloadedUpdate(arg1) {
  return window['go']['bindings']['UpdaterAPI']['OpenDownloadedUpdate'](arg1);
}

export function PerformUpdate() {
  return window['go']['bindings']['UpdaterAPI']['PerformUpdate']();
}

export function ShowDownloadedUpdate(arg1) {
  return window['go']['bindings']['UpdaterAPI']['ShowDownloadedUpdate'](arg1);
}
