// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function CheckForUpdate():Promise<bindings.SessionResponse>;

export function GetVersion():Promise<bindings.SessionResponse>;

export function PerformUpdate():Promise<bindings.SessionResponse>;
